### ISSUE TITLE
Duplicate sites in site reference sheet

### ISSUE THREAD

**Issue by GeoDan87** [NYC-Parks/consolidation_crowds_data#1]
I found these duplicate values in the PROPERTY_I column and they should be removed to allow the push to the database.

Q052-01
M198
M404
X039-ZN19
M042-ZN04
M071-37
M071-38
X044

**Comment by SVisovsky-NYCDPR** [comment]
Q052-01: One of the desc_locations has two spaces between "Tilly" and "Park", the other only has one. 

M198: I added one that does NOT have a comma after "King" because that's what UPS had.

M404: The original one in  the list had it's apostrophe corrupted somewhere between being a google sheet, sql result, feature class, dataframe, and csv. 

X039-ZN19: I got lazy when creating a single Orchard Beach for UPS. X039-ZN19 is actually Orchard Beach South. We should change the ID of this one or convince UPS to use Orchard Beach North/South.

M042-ZN04: I added a new row for this one because that's the best thing I could find to match "Dyckman Ballfield", which UPS wanted.

M071-37/M071-38: I'm confused as to how these are in there twice. I added them because they weren't joining. We should only need one.

X044: this one also didn't join in tableau for some reason. We should only need one.

**Comment by GeoDan87** [comment]
This issue is still preventing moving forward on automating the data ingestion into SQL. 

Here is my proposal: 
1. UPS is notified that their custom site names are being removed and replaced with the site names used by the ENTIRE REST OF NYC PARKS AND NYC. 
2. Their site names are removed and replaced with the actual names. 
3. We lock their edit access to the Google Form so they can no longer change these values.
4. The Ambassador and Patrol forms get updated.
5. Sites are added through a request to IPM. If the site is already named, but they disagree, UPS is referred to take these issues up with the Commissioners Office, City Council or the State Legislature.

**Comment by GeoDan87** [comment]
Created new site reference list and updated form dropdowns
