### ISSUE TITLE
Site name mismatches in Patrol sheets

### ISSUE THREAD

**Issue by GeoDan87** [NYC-Parks/consolidation_crowds_data#3]
I found several sites in the consolidated patrol sheet that don't exist in the [site reference list](https://docs.google.com/spreadsheets/d/1sqxyN7__7UuVSP-bxY3K0rkWqGvfNwi8mm1eDoc2hO0/edit#gid=0). The table below summarizes the issues that I found. I attempted to find the matching site in the reference table and I was pretty certain for all of them except the Parade Place entry. My guess is that someone edited the response to the "Which site are you reporting on?" question. If we haven't done so, I would suggest locking this column for edits in all sheets.

|Which site are you reporting on? (Patrol) |DESCRIPTIO (Site Reference)           |
|---------------------------------------------|---------------------------------------|
|Lower Highland Park (B)| Highland Park-Lower Highland Playground (Q020-01)|
|Yellowstone Municipal Park-Katzman Playground (Q)| Yellowstone Park (Q425) | 
|Baisley Pond Park-155th St Playground (Q)|Baisley Pond Park-157th St Playground (Q005-05)|
|Uncle Vito F. Maranzano Glendale Playground (Q)|"Uncle" Vito F. Maranzano Glendale Playground (Q290)|
|St James Park (X)|St James Park-St James Park (X044-01)|
|Parade Place (B)|Parade Ground(B068)|

If we don't correct these and prevent data entry mistakes from making their way into the sheets, it's actually impossible to automate anything.

Adding anyone that has touched this data for awareness.

**Comment by SVisovsky-NYCDPR** [comment]
I'm glad I thought to check here before I went and did anything rash. The sites you've identified are the ones that are still producing null geometries in the tableau dashboard (predominantly Highland).  I want to go in and change all the values in the forms and borough sheets for Yellowstone, St James, and Parade Place so that they match the site list and Uncle Vito to whichever version doesn't have quotes (because f quotes). 

We should double check to make sure there isn't a second playground in Baisley Pond at 155th in addition to the one at 157th - there may be one that got retired by OMP.

Lower Highland is a special thing. They want it to be the entire lower section of Highland Park, not just the playground.

**Comment by SVisovsky-NYCDPR** [comment]
I did add a thing for Lower Highland, since it represents the lions share of remaining null values.

**Comment by GeoDan87** [comment]
@SVisovsky-NYCDPR  Thank you for investigating further and making the changes! I’ll follow up next week if I have more questions.
