### ISSUE TITLE
Site Name Description in M&O Crowds

### ISSUE THREAD

**Issue by GeoDan87** [NYC-Parks/consolidation_crowds_data#9]
I found several sites in the consolidated crowd sheet [site reference list](https://docs.google.com/spreadsheets/d/1sqxyN7__7UuVSP-bxY3K0rkWqGvfNwi8mm1eDoc2hO0/edit#gid=0). The table below summarizes the issues that I found. Some of this may have to do with special characters.

|Site (Crowds) |DESCRIPTIO (Site Reference)           |
|---------------------------------------------|---------------------------------------|
|Q162I01 &#124; O'donohue Park| NOT IN SHEET|
|X044 &#124;  St. James Park|See #1 |
|M042-ZN04 &#124; Inwood Hill Park Zone 4 (Dyckman Fields)| See #1|
|X039-ZN19 &#124;  Pelham Bay Park-Orchard Beach South|See #1 |
|M071-ZN20 &#124;  Riverside Park-Hudson Beach Volleyball Courts & Caf├⌐|M071-ZN20 &#124;  Riverside Park-Hudson Beach Volleyball Courts & CafΓö£ΓîÉ|

O'donohue Park and Riverside Park are both new. It doesn't appear that O'donohue Park is in the site reference sheet. Riverside Park Zone 20 appears to have some kind of special character issue (I blame ESRI because what better scapegoat). The others are related to #1.

cc: @leightami

**Comment by SVisovsky-NYCDPR** [comment]
O'donohue is definitely a special characters thing when it comes to Google Sheets. That apostrophe throws off any formula you use that does anything with strings. 

I believe St.  James was the same (which is why there might be two).

Dyckman Fields and Orchard Beach South are probably artifacts of UPS having sites that don't line up with ours (Dyckman Fields zone is I think retired, but I'm not actually certain it's even the place UPS thinks it is, they just have one "orchard beach")

Hudson beach volleyball courts clearly got eaten by an elder god and we should forget they exist lest we risk our immortal souls. (probably the accent mark on "cafe" screwed it up)

**Comment by GeoDan87** [comment]
@SVisovsky-NYCDPR thank you for looking into the two new sites! 
- I couldn't find the omppropid for O'donohue Park in the Site Reference sheet. Is there issues with adding O'donohue to the site list? 
- Can we remove or update the duplicate sites (anything that UPS needs can be given a new UPS ID) from the site list sheet? 
-  Perhaps we can just update the description of M071-ZN20 in the site list and the dropdown? 
- I think we need to figure out which dropdown choices deviate from the site list.

cc: @leightami @IPM-Annette @sesquibe @julietsitron
